// Generated by gencpp from file plan_env/lec4Response.msg
// DO NOT EDIT!


#ifndef PLAN_ENV_MESSAGE_LEC4RESPONSE_H
#define PLAN_ENV_MESSAGE_LEC4RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plan_env
{
template <class ContainerAllocator>
struct lec4Response_
{
  typedef lec4Response_<ContainerAllocator> Type;

  lec4Response_()
    : is_valid(false)  {
    }
  lec4Response_(const ContainerAllocator& _alloc)
    : is_valid(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;





  typedef boost::shared_ptr< ::plan_env::lec4Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_env::lec4Response_<ContainerAllocator> const> ConstPtr;

}; // struct lec4Response_

typedef ::plan_env::lec4Response_<std::allocator<void> > lec4Response;

typedef boost::shared_ptr< ::plan_env::lec4Response > lec4ResponsePtr;
typedef boost::shared_ptr< ::plan_env::lec4Response const> lec4ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_env::lec4Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_env::lec4Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plan_env::lec4Response_<ContainerAllocator1> & lhs, const ::plan_env::lec4Response_<ContainerAllocator2> & rhs)
{
  return lhs.is_valid == rhs.is_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plan_env::lec4Response_<ContainerAllocator1> & lhs, const ::plan_env::lec4Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plan_env

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plan_env::lec4Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_env::lec4Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_env::lec4Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_env::lec4Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_env::lec4Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_env::lec4Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_env::lec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf1cc1d88653066e9e865909bc165df6";
  }

  static const char* value(const ::plan_env::lec4Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf1cc1d88653066eULL;
  static const uint64_t static_value2 = 0x9e865909bc165df6ULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_env::lec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_env/lec4Response";
  }

  static const char* value(const ::plan_env::lec4Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_env::lec4Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_valid\n"
"\n"
;
  }

  static const char* value(const ::plan_env::lec4Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_env::lec4Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lec4Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_env::lec4Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_env::lec4Response_<ContainerAllocator>& v)
  {
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_ENV_MESSAGE_LEC4RESPONSE_H
