// Generated by gencpp from file plan_env/lec4.msg
// DO NOT EDIT!


#ifndef PLAN_ENV_MESSAGE_LEC4_H
#define PLAN_ENV_MESSAGE_LEC4_H

#include <ros/service_traits.h>


#include <plan_env/lec4Request.h>
#include <plan_env/lec4Response.h>


namespace plan_env
{

struct lec4
{

typedef lec4Request Request;
typedef lec4Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lec4
} // namespace plan_env


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plan_env::lec4 > {
  static const char* value()
  {
    return "49905607991db81d6757177b80bef3dc";
  }

  static const char* value(const ::plan_env::lec4&) { return value(); }
};

template<>
struct DataType< ::plan_env::lec4 > {
  static const char* value()
  {
    return "plan_env/lec4";
  }

  static const char* value(const ::plan_env::lec4&) { return value(); }
};


// service_traits::MD5Sum< ::plan_env::lec4Request> should match
// service_traits::MD5Sum< ::plan_env::lec4 >
template<>
struct MD5Sum< ::plan_env::lec4Request>
{
  static const char* value()
  {
    return MD5Sum< ::plan_env::lec4 >::value();
  }
  static const char* value(const ::plan_env::lec4Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_env::lec4Request> should match
// service_traits::DataType< ::plan_env::lec4 >
template<>
struct DataType< ::plan_env::lec4Request>
{
  static const char* value()
  {
    return DataType< ::plan_env::lec4 >::value();
  }
  static const char* value(const ::plan_env::lec4Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plan_env::lec4Response> should match
// service_traits::MD5Sum< ::plan_env::lec4 >
template<>
struct MD5Sum< ::plan_env::lec4Response>
{
  static const char* value()
  {
    return MD5Sum< ::plan_env::lec4 >::value();
  }
  static const char* value(const ::plan_env::lec4Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_env::lec4Response> should match
// service_traits::DataType< ::plan_env::lec4 >
template<>
struct DataType< ::plan_env::lec4Response>
{
  static const char* value()
  {
    return DataType< ::plan_env::lec4 >::value();
  }
  static const char* value(const ::plan_env::lec4Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAN_ENV_MESSAGE_LEC4_H
