// Generated by gencpp from file key_sim/lec4.msg
// DO NOT EDIT!


#ifndef KEY_SIM_MESSAGE_LEC4_H
#define KEY_SIM_MESSAGE_LEC4_H

#include <ros/service_traits.h>


#include <key_sim/lec4Request.h>
#include <key_sim/lec4Response.h>


namespace key_sim
{

struct lec4
{

typedef lec4Request Request;
typedef lec4Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lec4
} // namespace key_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::key_sim::lec4 > {
  static const char* value()
  {
    return "49905607991db81d6757177b80bef3dc";
  }

  static const char* value(const ::key_sim::lec4&) { return value(); }
};

template<>
struct DataType< ::key_sim::lec4 > {
  static const char* value()
  {
    return "key_sim/lec4";
  }

  static const char* value(const ::key_sim::lec4&) { return value(); }
};


// service_traits::MD5Sum< ::key_sim::lec4Request> should match
// service_traits::MD5Sum< ::key_sim::lec4 >
template<>
struct MD5Sum< ::key_sim::lec4Request>
{
  static const char* value()
  {
    return MD5Sum< ::key_sim::lec4 >::value();
  }
  static const char* value(const ::key_sim::lec4Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_sim::lec4Request> should match
// service_traits::DataType< ::key_sim::lec4 >
template<>
struct DataType< ::key_sim::lec4Request>
{
  static const char* value()
  {
    return DataType< ::key_sim::lec4 >::value();
  }
  static const char* value(const ::key_sim::lec4Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::key_sim::lec4Response> should match
// service_traits::MD5Sum< ::key_sim::lec4 >
template<>
struct MD5Sum< ::key_sim::lec4Response>
{
  static const char* value()
  {
    return MD5Sum< ::key_sim::lec4 >::value();
  }
  static const char* value(const ::key_sim::lec4Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_sim::lec4Response> should match
// service_traits::DataType< ::key_sim::lec4 >
template<>
struct DataType< ::key_sim::lec4Response>
{
  static const char* value()
  {
    return DataType< ::key_sim::lec4 >::value();
  }
  static const char* value(const ::key_sim::lec4Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KEY_SIM_MESSAGE_LEC4_H
